name: Workflow
on:
  push:
    branches: [ test-using-version-folder-for-replace ]
  pull_request:
    branches: [ test-using-version-folder-for-replace ]
jobs:
  code-check:
    name: Check Go formatting, linting, vetting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Checkout gofsutil
        uses: actions/checkout@v2
        with:
          repository: 'dell/gofsutil'
          path: 'vendor/gofsutil'
      - name: Checkout goscaleio
        uses: actions/checkout@v2
        with:
          repository: 'dell/goscaleio'
          path: 'vendor/goscaleio'
      - name: Run the formatter, linter, and vetter
        uses: dell/common-github-actions/go-code-formatter-linter-vetter@main
        with:
          directories: ./...
  test:
    name: Run Go unit tests and check package coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout csi-powerflex
        uses: actions/checkout@v2
      - name: Checkout gofsutil
        uses: actions/checkout@v2
        with:
          repository: 'dell/gofsutil'
          path: 'vendor/gofsutil'
      - name: Checkout goscaleio
        uses: actions/checkout@v2
        with:
          repository: 'dell/goscaleio'
          path: 'vendor/goscaleio'
      - name: Run unit tests and check package coverage
        uses: dell/common-github-actions/go-code-tester@pflex-unit-test-no-race
        with:
          threshold: 90
          test-folder: "./service"
  go_security_scan:
    name: Go security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Checkout gofsutil
        uses: actions/checkout@v2
        with:
          repository: 'dell/gofsutil'
          path: 'vendor/gofsutil'
      - name: Checkout goscaleio
        uses: actions/checkout@v2
        with:
          repository: 'dell/goscaleio'
          path: 'vendor/goscaleio'
      - name: Run Go Security
        uses: securego/gosec@master
        with:
          # added additional exclude arguments after gosec v2.9.4 came out
          args: -exclude=G108,G301,G302,G304,G307,G402 ./...
  malware_security_scan:
    name: Malware Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run malware scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
